"""initial_schema

Revision ID: a26aab1eac22
Revises: 
Create Date: 2026-03-10 11:22:18.432816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a26aab1eac22'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drink_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_name', sa.String(length=200), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drink_sessions_id'), 'drink_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_drink_sessions_is_active'), 'drink_sessions', ['is_active'], unique=False)
    op.create_table('drinks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('alcohol_content', sa.DECIMAL(precision=4, scale=2), nullable=False),
    sa.Column('flavor_profile', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_spirit', sa.String(length=100), nullable=True),
    sa.Column('ingredients', sa.JSON(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drinks_category'), 'drinks', ['category'], unique=False)
    op.create_index(op.f('ix_drinks_id'), 'drinks', ['id'], unique=False)
    op.create_index(op.f('ix_drinks_name'), 'drinks', ['name'], unique=False)
    op.create_table('consumed_drinks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('drink_id', sa.Integer(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('drink_order', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['drink_id'], ['drinks.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['drink_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumed_drinks_drink_id'), 'consumed_drinks', ['drink_id'], unique=False)
    op.create_index(op.f('ix_consumed_drinks_id'), 'consumed_drinks', ['id'], unique=False)
    op.create_index(op.f('ix_consumed_drinks_session_id'), 'consumed_drinks', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consumed_drinks_session_id'), table_name='consumed_drinks')
    op.drop_index(op.f('ix_consumed_drinks_id'), table_name='consumed_drinks')
    op.drop_index(op.f('ix_consumed_drinks_drink_id'), table_name='consumed_drinks')
    op.drop_table('consumed_drinks')
    op.drop_index(op.f('ix_drinks_name'), table_name='drinks')
    op.drop_index(op.f('ix_drinks_id'), table_name='drinks')
    op.drop_index(op.f('ix_drinks_category'), table_name='drinks')
    op.drop_table('drinks')
    op.drop_index(op.f('ix_drink_sessions_is_active'), table_name='drink_sessions')
    op.drop_index(op.f('ix_drink_sessions_id'), table_name='drink_sessions')
    op.drop_table('drink_sessions')
    # ### end Alembic commands ###
